### ISSUE TITLE
Cannot Run Demo "mainScan.m"

### ISSUE THREAD

**Issue by ShannonZ** [mathieuboudreau/T1mapping_060210#1]
Undefined function or variable 'extra'.

Error in T1ScanExperiment (line 22)
nlsS = getNLSStruct(extra,1);

Error in mainScan (line 36)
T1ScanExperiment(loadStr, saveStr, method);

**Comment by mathieuboudreau** [comment]
Thanks for letting me know!

It appears that this but is present in the original code: http://www-mrsrl.stanford.edu/~jbarral/t1map.html

I'm unavailable to debug this at the moment, however this (Barral's) code has been implemented into a larger quantitative MRI project, [qMRLab](https://github.com/qmrlab/qmrlab), so I recommend you try the demo in that software to process inversion recovery data. It is more maintained and up-to-date than this project/Barral's website, and also has a graphical user interface available.

**Comment by mathieuboudreau** [comment]
Hi @ShannonZ,

I hope you are well.

I've resolved this issue in commit 93e251c4690d26658d00714f3c4f88909c94d2fd, and added a demo dataset courtesy of [qMRLab](https://github.com/qMRLab/qMRLab). I recommend you check out that software if you need any additional T1 mapping processing needs.

Best regards,

Mathieu

**Comment by ShannonZ** [comment]
> Hi @ShannonZ,
> 
> I hope you are well.
> 
> I've resolved this issue in commit [93e251c](https://github.com/mathieuboudreau/Gold-Standard-Inversion-Recovery-T1-Mapping/commit/93e251c4690d26658d00714f3c4f88909c94d2fd), and added a demo dataset courtesy of [qMRLab](https://github.com/qMRLab/qMRLab). I recommend you check out that software if you need any additional T1 mapping processing needs.
> 
> Best regards,
> 
> Mathieu

Thanks Mathieu. It works well now. BTW, Is rdNlsPr.m suitable for T2 mapping? I think the model |ra + rb*exp(-t/T1)| is a more generalized version of |rb*exp(-t/T2)|.

**Comment by mathieuboudreau** [comment]
Hi @ShannonZ,

I haven't explored that, but I don't think so. I believe the `ra` portion contains some part that takes into account the regrowth of the signal to equilibrium M0, which doesn't happen for T2. There are a lot of quantitative tools to fit for multi-exponential T2 mapping though, to see some explore [qMRLab](https://github.com/qMRLab/qMRLab), [MERA](https://vuiis.vumc.org/~doesmd/MERA/MERA_Toolbox.html), or [AnalyzeNNLS](https://sourceforge.net/projects/analyzennls/).

**Comment by ShannonZ** [comment]
Thank you for your prompt reply. I've tried qMRLab and  found the embeded T2 mapping works well.
